version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ec2-user/p2papi/nginx.conf:/etc/nginx/nginx.conf
      - /home/ec2-user/ssl:/ssl/
        
  p2papi-uat:
    depends_on:
        - nginx
    image: p2papi
    container_name: p2papi
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    volumes:
      - /home/ec2-user/p2papi/p2papi:/app/
